### ISSUE TITLE
BaseTest has two insuppressible warnings, causing test failure

### ISSUE THREAD

**Issue by CuylerE-WP** [Wheel-Pros-IT/wp-fitment-api-php-client#2]
running /vendor/bin/phpunit with all environment variables set properly does allow all tests to pass - but two warnings get generated that cause the command to exit with a status code of 1, causing failure.

Warning 1: ...\Wheelpros\FitmentPlatformApi\Tests\BaseTest declared in ...\Tests\BaseTest is abstract

this can be resolved by removing the 'abstract' modifier from the class.

Warning 2:  No tests found in class "Wheelpros\FitmentPlatformApi\Tests\BaseTest

this can be resolved by either renaming BaseTest to something without the "Test" suffix, or by moving it to a trait which can be used in other tests, or by creating a test to use in the class.

**Comment by jesse-greathouse** [comment]
Thanks @CuylerE-WP 

A fix for this has been included in #1 and it will be merged to main and tagged as 1.0.1 tomorrow

**Comment by jesse-greathouse** [comment]
Fixed in release [1.0.1](https://github.com/Wheel-Pros-IT/wp-fitment-api-php-client/releases/tag/1.0.1).
